// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoHMZHn-vriuD_okSLUXIAV6czS8yyd_E',
    appId: '1:870208891269:web:c8507c0253f5cc2c0cbcec',
    messagingSenderId: '870208891269',
    projectId: 'goski-student',
    authDomain: 'goski-student.firebaseapp.com',
    storageBucket: 'goski-student.appspot.com',
    measurementId: 'G-D0SNXBW97R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp2op3a8NpPDmxWoOgS_XpaR4o5XFuiII',
    appId: '1:870208891269:android:16938c55cb4cb1290cbcec',
    messagingSenderId: '870208891269',
    projectId: 'goski-student',
    storageBucket: 'goski-student.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDyVauuM4SMY9s-F9m9m43_L_NFGqlVZ0',
    appId: '1:870208891269:ios:183532f35bb604050cbcec',
    messagingSenderId: '870208891269',
    projectId: 'goski-student',
    storageBucket: 'goski-student.appspot.com',
    iosBundleId: 'com.example.goskiStudent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDyVauuM4SMY9s-F9m9m43_L_NFGqlVZ0',
    appId: '1:870208891269:ios:6dbbbec068f623a60cbcec',
    messagingSenderId: '870208891269',
    projectId: 'goski-student',
    storageBucket: 'goski-student.appspot.com',
    iosBundleId: 'com.example.goskiStudent.RunnerTests',
  );
}
